keys:
  - &admin_kevin age1mxryupgwdk3rd8vx6l0gkgsccdnlnfpagd4w675wpdj5qtmwd5kqp75rg8
  - &host_ray age1udsnzrehdy2hzgsvqu3je7uq9t0cue27slusps7r04l3gc7dk5fqcug5zq
  - &host_rex age1cmz3s2chhggv8656fj08zdqtjz3q4cyu5rcy7a4j629zzycak3us7ax3dq
  - &host_raven age1j6cjs3kf26u8n0au6z2npp0hgr6ul0spu3zrz5u4epnqkpm6mezqekt7lu
creation_rules:
  - path_regex: .*/[^/]*secrets\.(yaml|json)$
    key_groups:
      - age:
        - *admin_kevin
        - *host_ray
        - *host_rex
        - *host_raven
