keys:
  - &admin_kevin age1mxryupgwdk3rd8vx6l0gkgsccdnlnfpagd4w675wpdj5qtmwd5kqp75rg8
  - &host_ray age1udsnzrehdy2hzgsvqu3je7uq9t0cue27slusps7r04l3gc7dk5fqcug5zq
  - &host_rex age1cmz3s2chhggv8656fj08zdqtjz3q4cyu5rcy7a4j629zzycak3us7ax3dq
  - &host_testvm age1528wp0vu9eecjectd2aw2wq9l2csgmxmj973vk0ypxf6c735x9lshl5fhq
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_kevin
        - *host_ray
        - *host_rex
        - *host_testvm
